const genres = [
    "acid house",
    "acid jazz",
    "acoustic blues",
    "acoustic rock",
    "afrobeat",
    "alternative country",
    "alternative dance",
    "alternative folk",
    "alternative hip hop",
    "alternative metal",
    "alternative pop",
    "alternative punk",
    "alternative rock",
    "ambient",
    "americana",
    "anarcho-punk",
    "aor",
    "arena rock",
    "art rock",
    "atmospheric black metal",
    "audiobook",
    "avant-garde",
    "avant-garde jazz",
    "avant-garde metal",
    "avant-garde pop",
    "bachata",
    "ballad",
    "baroque",
    "bebop",
    "bhangra",
    "big band",
    "big beat",
    "black metal",
    "blackened death metal",
    "blue-eyed soul",
    "bluegrass",
    "blues",
    "blues rock",
    "bolero",
    "bossa nova",
    "breakbeat",
    "breakcore",
    "breaks",
    "britpop",
    "broken beat",
    "brutal death metal",
    "bubblegum pop",
    "celtic",
    "chamber pop",
    "chanson",
    "chicago blues",
    "chillout",
    "chiptune",
    "christian rock",
    "christmas music",
    "classic blues",
    "classic country",
    "classic jazz",
    "classic rock",
    "classical",
    "club",
    "comedy",
    "conscious hip hop",
    "contemporary christian",
    "contemporary classical",
    "contemporary folk",
    "contemporary gospel",
    "contemporary jazz",
    "contemporary r&b",
    "contra",
    "cool jazz",
    "country",
    "country blues",
    "country folk",
    "country pop",
    "country rock",
    "cumbia",
    "dance",
    "dance-pop",
    "dance-punk",
    "dancehall",
    "dark ambient",
    "dark electro",
    "dark folk",
    "dark wave",
    "death metal",
    "death-doom metal",
    "deathcore",
    "deathrock",
    "deep house",
    "delta blues",
    "digital hardcore",
    "disco",
    "doo-wop",
    "doom metal",
    "downtempo",
    "drone",
    "drum and bass",
    "dub",
    "dub techno",
    "dubstep",
    "east coast hip hop",
    "ebm",
    "electric blues",
    "electro",
    "electro house",
    "electro-funk",
    "electro-industrial",
    "electroclash",
    "electronic",
    "electronic rock",
    "electronica",
    "electropop",
    "electropunk",
    "emo",
    "emocore",
    "ethereal",
    "euro house",
    "eurodance",
    "europop",
    "experimental",
    "experimental rock",
    "filk",
    "flamenco",
    "folk",
    "folk metal",
    "folk punk",
    "folk rock",
    "folk pop",
    "freak folk",
    "free improvisation",
    "free jazz",
    "funk",
    "funk carioca",
    "funk metal",
    "funk rock",
    "funk soul",
    "funky house",
    "fusion",
    "future jazz",
    "futurepop",
    "gabber",
    "gangsta rap",
    "garage",
    "garage house",
    "garage rock",
    "glam",
    "glam metal",
    "glam rock",
    "glitch",
    "goa trance",
    "gospel",
    "gothic",
    "gothic metal",
    "gothic rock",
    "grime",
    "grindcore",
    "groove metal",
    "grunge",
    "happy hardcore",
    "hard bop",
    "hard house",
    "hard rock",
    "hard trance",
    "hardcore techno",
    "hardcore punk",
    "hardstyle",
    "heavy metal",
    "hip hop",
    "honky tonk",
    "horror punk",
    "house",
    "idm",
    "illbient",
    "indie",
    "indie folk",
    "indie pop",
    "indie rock",
    "indietronica",
    "indorock",
    "industrial",
    "industrial metal",
    "industrial rock",
    "instrumental",
    "instrumental jazz",
    "instrumental rock",
    "irish folk",
    "italo-disco",
    "j-pop",
    "j-rock",
    "jazz",
    "jazz blues",
    "jazz fusion",
    "jazz rap",
    "jazz rock",
    "jazz-funk",
    "jungle",
    "k-pop",
    "krautrock",
    "latin",
    "latin jazz",
    "latin pop",
    "latin rock",
    "leftfield",
    "line dance",
    "lo-fi",
    "lounge",
    "madchester",
    "mainstream rock",
    "mambo",
    "martial industrial",
    "math rock",
    "mathcore",
    "medieval",
    "melodic black metal",
    "melodic death metal",
    "melodic metalcore",
    "melodic rock",
    "melodic trance",
    "merengue",
    "metal",
    "metalcore",
    "minimal",
    "modern blues",
    "modern classical",
    "modern country",
    "motown",
    "mpb",
    "musical",
    "neo soul",
    "neofolk",
    "new age",
    "new romantic",
    "new wave",
    "no wave",
    "noise",
    "noise pop",
    "non-music",
    "norteño",
    "northern soul",
    "nu jazz",
    "nu metal",
    "oi",
    "old school death metal",
    "opera",
    "orchestral",
    "pop",
    "pop metal",
    "pop punk",
    "pop rap",
    "pop rock",
    "pop soul",
    "post-bop",
    "post-classical",
    "post-grunge",
    "post-hardcore",
    "post-metal",
    "post-punk",
    "post-rock",
    "power electronics",
    "power metal",
    "power pop",
    "production music",
    "progressive",
    "progressive house",
    "progressive metal",
    "progressive rock",
    "progressive trance",
    "psy-trance",
    "psychedelic",
    "psychedelic folk",
    "psychedelic pop",
    "psychedelic rock",
    "psychobilly",
    "psytrance",
    "punk",
    "punk rock",
    "r&b",
    "ragga",
    "ragga hip-hop",
    "ranchera",
    "rap rock",
    "rapcore",
    "rave",
    "reggae",
    "reggaeton",
    "rhythmic noise",
    "rock",
    "rock and roll",
    "rockabilly",
    "roots reggae",
    "rumba",
    "salsa",
    "samba",
    "schlager",
    "screamo",
    "shoegaze",
    "singer-songwriter",
    "ska",
    "ska punk",
    "skacore",
    "slow waltz",
    "sludge metal",
    "smooth jazz",
    "smooth soul",
    "soft rock",
    "soul",
    "soul jazz",
    "southern rock",
    "southern soul",
    "space rock",
    "speed metal",
    "spoken word",
    "stoner metal",
    "stoner rock",
    "street punk",
    "surf rock",
    "swing",
    "symphonic black metal",
    "symphonic metal",
    "symphonic prog",
    "symphonic rock",
    "symphony",
    "synth-pop",
    "tango",
    "tech house",
    "technical death metal",
    "techno",
    "teen pop",
    "thrash metal",
    "traditional country",
    "trance",
    "tribal house",
    "trip hop",
    "turntablism",
    "uk garage",
    "underground hip hop",
    "viking metal",
    "vocal house",
    "vocal jazz",
    "vocal trance",
    "west coast hip hop",
    "west coast swing"
]

export const genreList = Object.assign({}, genres);


